import {listProducts,validateProduct,digest,applyProducts} from './store';
export function money(value:unknown){if(typeof value==='number'){if(!Number.isFinite(value)||value<0)throw Error('Preço inválido');return Math.round(value*100);}if(typeof value!=='string')throw Error('Preço inválido');let s=value.trim().replace(/^R\$\s*/,'');if(s.includes(',')){if(!/^(?:\d+|\d{1,3}(?:\.\d{3})+),\d{1,2}$/.test(s))throw Error('Preço inválido: '+value);s=s.replace(/\./g,'').replace(',','.');}else if(!/^\d+(?:\.\d{1,2})?$/.test(s))throw Error('Preço inválido: '+value);return Math.round(Number(s)*100);}
function csv(source:string){const delimiter=source.split(/\r?\n/,1)[0].includes(';')?';':',';const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<source.length;i++){const c=source[i];if(c==='"'){if(quoted&&source[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(!quoted&&c===delimiter){row.push(cell);cell='';}else if(!quoted&&(c==='\n'||c==='\r')){if(c==='\r'&&source[i+1]==='\n')i++;row.push(cell);if(row.some(c=>c.trim()))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('Aspas não fechadas no CSV.');row.push(cell);if(row.some(c=>c.trim()))rows.push(row);const headers=rows.shift()?.map(h=>h.trim().replace(/^\uFEFF/,''));if(!headers?.length||new Set(headers).size!==headers.length)throw Error('Cabeçalho inválido/duplicado.');return rows.map((values,i)=>{if(values.length!==headers.length)throw Error('Quantidade de colunas inválida na linha '+(i+2));return Object.fromEntries(headers.map((h,j)=>[h,values[j]]));});}
const keys:Record<string,string>={codigo:'id',nome:'name',categoria:'category',descricao:'description',imagem:'image',texto_imagem:'alt',preco:'priceInCents',preco_promocional:'promoPriceInCents',inicio_promocao:'promoStart',fim_promocao:'promoEnd',habilitado:'enabled',disponivel:'available',demonstrativo:'demo',opcoes:'variants',colecoes:'collections',tags:'tags',slug:'slug'};
const bool=(v:any)=>{if(typeof v==='boolean')return v;if(['sim','true','1'].includes(String(v).toLowerCase()))return true;if(['não','nao','false','0'].includes(String(v).toLowerCase()))return false;throw Error('Use sim/não para situações.');};
export async function previewImport(input:any){
 if(!input||typeof input.text!=='string'||input.text.length>1000000)throw Error('Lista deve ter até 1 MB.');
 const rows=input.format==='json'?JSON.parse(input.text):csv(input.text);if(!Array.isArray(rows)||!rows.length||rows.length>500)throw Error('Importe de 1 a 500 produtos por vez.');
 const products=new Map((await listProducts(true)).map(p=>[p.id,p]));
 const seen=new Set<string>();const changes:any[]=[];const summary:any[]=[];const versions:any[]=[];
 rows.forEach((row:any,index:number)=>{try{if(!row||typeof row!=='object'||Array.isArray(row))throw Error('Linha inválida.');const id=String(row.codigo??row.id??'').trim();if(!id)throw Error('Código obrigatório.');if(seen.has(id))throw Error('Código duplicado na lista.');seen.add(id);const before=products.get(id);versions.push([id,before?.revision||0]);if(before&&!input.overwrite){summary.push({line:index+1,id,status:'ignorado',detail:'Cadastro existente preservado'});return;}
 const mapped:any={};for(const [key,value]of Object.entries(row)){if(['revision','createdAt','updatedAt'].includes(key))continue;if(value===''||value===null||value===undefined)continue;const target=keys[key]||key;if(!['id','name','category','description','image','alt','priceInCents','promoPriceInCents','promoStart','promoEnd','enabled','available','demo','variants','collections','tags','slug'].includes(target))throw Error('Coluna desconhecida: '+key);mapped[target]=['preco','preco_promocional'].includes(key)?money(value):['enabled','available','demo'].includes(target)?bool(value):['variants','collections','tags'].includes(target)?(Array.isArray(value)?value:String(value).split('|').map(v=>v.trim()).filter(Boolean)):value;}
 const raw={id,slug:id.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),name:'',description:'',category:'',image:'',alt:'',collections:[],tags:[],variants:['Única'],promoPriceInCents:null,promoStart:'',promoEnd:'',enabled:false,available:true,demo:false,...before,...mapped};
 if(!raw.description&&raw.name)raw.description=raw.name+'. Consulte o atendimento para mais detalhes sobre esta peça.';
 const validated=validateProduct(raw,before);changes.push({...validated,revision:before?.revision||0});summary.push({line:index+1,id,status:before?'atualizar':'novo',detail:validated.name});
 }catch(e){summary.push({line:index+1,status:'erro',detail:(e as Error).message});}});
 const token=digest(JSON.stringify({text:input.text,format:input.format,overwrite:!!input.overwrite,versions}));return {summary,changes,token};
}
export async function commitImport(input:any){const preview=await previewImport(input);if(preview.token!==input.token)throw Error('Lista ou catálogo mudou. Gere a prévia novamente.');if(preview.summary.some(row=>row.status==='erro'))throw Error('Corrija os erros antes de importar.');const changed=await applyProducts(preview.changes,'importação '+(input.format==='json'?'JSON':'CSV'));return {saved:changed.length,ignored:preview.summary.filter(r=>r.status==='ignorado').length};}
