import type {CatalogProduct} from '../data/catalog';
import {formatPrice,effectivePrice} from '../data/catalog';
const $=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;
const feedback=(message:string)=>{$('#feedback').textContent=message;};
async function api(path:string,data?:unknown){const response=await fetch('/api/'+path,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(response.status===401){location.href='/admin/login';throw Error('Sessão encerrada.');}if(!response.ok)throw Error(result.error||'Não foi possível concluir.');return result;}
function action(fn:()=>Promise<void>){return async()=>{try{await fn();}catch(e){feedback((e as Error).message);}};}
function cell(row:HTMLTableRowElement,text:string){const c=row.insertCell();c.textContent=text;c.dataset.label=row.closest("table")?.querySelectorAll("thead th")[c.cellIndex]?.textContent||"";return c;}
function button(parent:HTMLElement,text:string,fn:()=>Promise<void>){const b=document.createElement('button');b.type='button';b.className='secondary';b.textContent=text;b.addEventListener('click',action(fn));parent.append(b);}
let products:CatalogProduct[]=[];
const editor=$<HTMLDialogElement>('#editor'),form=$<HTMLFormElement>('#product-form');
function field(name:string){return form.elements.namedItem(name) as HTMLInputElement;}
function render(){const search=$<HTMLInputElement>('#admin-search').value.toLocaleLowerCase('pt-BR');const status=$<HTMLSelectElement>('#admin-status').value;const rows=$<HTMLTableSectionElement>('#product-rows');rows.replaceChildren();for(const p of products.filter(p=>(p.name+' '+p.id).toLocaleLowerCase('pt-BR').includes(search)&&(!status||(status==='enabled'?p.enabled:!p.enabled)))){const row=rows.insertRow();cell(row,p.name+' · '+p.id);cell(row,formatPrice(effectivePrice(p)));cell(row,p.enabled?'Habilitado':'Desativado');cell(row,p.available?'Disponível':'Indisponível');const actions=row.insertCell();actions.dataset.label="Ações";button(actions,'Editar',async()=>openEditor(p));button(actions,p.enabled?'Desativar':'Reativar',async()=>{await api('products',{...p,enabled:!p.enabled});await load();feedback('Situação atualizada; histórico preservado.');});button(actions,'Histórico',async()=>{const records=await api('history?id='+encodeURIComponent(p.id));const content=$('#history-content');content.replaceChildren();for(const r of records){const d=document.createElement('details');const summary=document.createElement('summary');summary.textContent=new Date(r.at).toLocaleString('pt-BR')+' · '+r.source;const pre=document.createElement('pre');pre.textContent=JSON.stringify({responsavel:r.actor,antes:r.before_json?JSON.parse(r.before_json):null,depois:JSON.parse(r.after_json)},null,2);d.append(summary,pre);content.append(d);}$<HTMLDialogElement>('#history-dialog').showModal();});}}
async function load(){products=await api('products');render();}
const list=(s:string)=>s.split('|').map(v=>v.trim()).filter(Boolean);
function decimal(s:string){let value=s.trim();if(value.includes(','))value=value.replace(/\./g,'').replace(',','.');if(!/^\d+(?:\.\d{1,2})?$/.test(value))throw Error('Preço inválido; use 129,90.');return Math.round(Number(value)*100);}
function localDate(iso:string){if(!iso)return '';const date=new Date(iso);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);}
function openEditor(p?:CatalogProduct){form.reset();$('#editor-feedback').textContent='';$('#editor-title').textContent=p?'Editar '+p.name:'Cadastrar produto';for(const name of ['id','slug','name','category','image','alt','description'])field(name).value=p?String(p[name as keyof CatalogProduct]):name==='category'?'brincos':'';field('id').readOnly=!!p;field('revision').value=String(p?.revision||0);field('price').value=p?(p.priceInCents/100).toFixed(2).replace('.',','):'';field('promoPrice').value=p?.promoPriceInCents!=null?(p.promoPriceInCents/100).toFixed(2).replace('.',','):'';field('promoStart').value=localDate(p?.promoStart||'');field('promoEnd').value=localDate(p?.promoEnd||'');field('variants').value=p?.variants.join(' | ')||'Única';field('tags').value=p?.tags.join(' | ')||'';for(const name of ['enabled','available','demo'])field(name).checked=p?Boolean(p[name as keyof CatalogProduct]):name==='available';for(const option of ($<HTMLSelectElement>('[name="collections"]')).options)option.selected=p?.collections.includes(option.value)||false;editor.showModal();}
$('#new-product').addEventListener('click',()=>openEditor());document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog')?.close()));$('#admin-search').addEventListener('input',render);$('#admin-status').addEventListener('change',render);
field('name').addEventListener('input',()=>{if(!field('id').readOnly)field('slug').value=field('name').value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');});
$('#suggest-description').addEventListener('click',()=>{if(field('description').value.trim()&&!confirm('Substituir o texto pelo rascunho?'))return;field('description').value=field('name').value.trim()?field('name').value.trim()+'. Uma opção para compor suas combinações. Consulte o atendimento para conhecer os detalhes da peça.':'';});
form.addEventListener('submit',async e=>{e.preventDefault();const save=$<HTMLButtonElement>('#save-product');save.disabled=true;try{const data:any={};for(const name of ['id','slug','name','category','image','alt','description'])data[name]=field(name).value;data.revision=Number(field('revision').value);data.priceInCents=decimal(field('price').value);data.promoPriceInCents=field('promoPrice').value?decimal(field('promoPrice').value):null;for(const name of ['promoStart','promoEnd'])data[name]=field(name).value?new Date(field(name).value).toISOString():'';for(const name of ['enabled','available','demo'])data[name]=field(name).checked;data.tags=list(field('tags').value);data.variants=list(field('variants').value);data.collections=Array.from($<HTMLSelectElement>('[name="collections"]').selectedOptions).map(o=>o.value);await api('products',data);editor.close();await load();feedback('Produto salvo. O catálogo já reflete a alteração.');}catch(e){$('#editor-feedback').textContent=(e as Error).message;}finally{save.disabled=false;}});
$('#upload-image').addEventListener('change',async()=>{const save=$<HTMLButtonElement>('#save-product');save.disabled=true;try{const file=$<HTMLInputElement>('#upload-image').files?.[0];if(!file)return;const data=new FormData();data.set('image',file);const response=await fetch('/api/upload',{method:'POST',body:data});const result=await response.json();if(!response.ok)throw Error(result.error);field('image').value=result.image;$('#editor-feedback').textContent='Foto enviada. Salve o produto para associá-la.';}catch(e){$('#editor-feedback').textContent=(e as Error).message;}finally{save.disabled=false;}});
let previewToken='';function importData(){return {text:$<HTMLTextAreaElement>('#import-text').value,format:$<HTMLSelectElement>('#import-format').value,overwrite:$<HTMLInputElement>('#overwrite').checked};}
function invalidate(){previewToken='';$<HTMLButtonElement>('#apply-import').disabled=true;}
['#import-text','#import-format','#overwrite'].forEach(s=>$(s).addEventListener('input',invalidate));
$('#import-file').addEventListener('change',action(async()=>{const file=$<HTMLInputElement>('#import-file').files?.[0];if(!file)return;if(file.size>1000000)throw Error('Lista deve ter até 1 MB.');$<HTMLTextAreaElement>('#import-text').value=await file.text();$<HTMLSelectElement>('#import-format').value=file.name.toLowerCase().endsWith('.json')?'json':'csv';invalidate();}));
$('#preview-import').addEventListener('click',action(async()=>{invalidate();const result=await api('import-preview',importData());previewToken=result.token;const table=document.createElement('table');const header=table.createTHead().insertRow();for(const text of ['Linha','Código','Resultado','Detalhes']){const th=document.createElement('th');th.textContent=text;header.append(th);}const body=table.createTBody();for(const item of result.summary){const row=body.insertRow();for(const value of [item.line,item.id||'',item.status,item.detail])cell(row,String(value));}$('#import-result').replaceChildren(table);$<HTMLButtonElement>('#apply-import').disabled=result.summary.some((r:any)=>r.status==='erro');feedback('Prévia pronta. Confira os resultados antes de confirmar.');}));
$('#apply-import').addEventListener('click',action(async()=>{const btn=$<HTMLButtonElement>('#apply-import');btn.disabled=true;const result=await api('import-apply',{...importData(),token:previewToken});invalidate();await load();feedback(result.saved+' produtos salvos; '+result.ignored+' existentes preservados.');}));
async function loadRequests(){const records=await api('requests');const target=$('#request-rows');target.replaceChildren();if(!records.length){target.textContent='Nenhuma solicitação registrada ainda.';return;}for(const r of records){const d=document.createElement('details');const summary=document.createElement('summary');summary.textContent=r.name+' · '+r.phone+' · '+formatPrice(r.subtotalInCents)+' · '+r.status;const pre=document.createElement('pre');pre.textContent=new Date(r.createdAt).toLocaleString('pt-BR')+'\n'+r.message;const label=document.createElement('label');label.textContent='Situação do atendimento';const select=document.createElement('select');for(const value of ['nova','em atendimento','concluída','cancelada']){const o=document.createElement('option');o.value=value;o.textContent=value;select.append(o);}select.value=r.status;label.append(select);select.addEventListener('change',action(async()=>{await api('request-status',{id:r.id,status:select.value});await loadRequests();feedback('Atendimento atualizado.');}));const pdf=document.createElement('button');pdf.textContent='Baixar PDF com fotos';pdf.addEventListener('click',action(async()=>{pdf.disabled=true;try{const response=await fetch('/api/request-pdf',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:r.id})});if(!response.ok)throw Error('Não foi possível gerar o PDF.');const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download='alejoias-'+r.id+'.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}finally{pdf.disabled=false;}}));d.append(summary,pre,pdf,label);target.append(d);}}
$('#refresh-requests').addEventListener('click',action(loadRequests));$('#logout').addEventListener('click',action(async()=>{await api('logout',{});location.href='/admin/login';}));$('#password-form').addEventListener('submit',e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget as HTMLFormElement));void action(async()=>{await api('password',values);location.href='/admin/login';})();});
void action(async()=>{await load();await loadRequests();})();
